name: Update wy.js Plugin

on:
  repository_dispatch:
    types: [check_for_updates]
  workflow_dispatch:
  schedule:
    - cron: '*/10 * * * *'

jobs:
  check-upstream:
    runs-on: ubuntu-latest
    outputs:
      has_update: ${{ steps.check-update.outputs.has_update }}
    steps:
      - name: Check upstream repository status
        id: check-update
        run: |
          # 安装依赖
          sudo apt-get update
          sudo apt-get install -y jq curl
          
          # 获取上游仓库最新 commit SHA
          UPSTREAM_SHA=$(curl -s "https://api.github.com/repos/ThomasBy2025/musicfree/commits/main" | jq -r .sha)
          
          # 获取上次记录的 commit SHA
          if [ -f .last_commit ]; then
            LAST_SHA=$(cat .last_commit)
          else
            LAST_SHA=""
          fi
          
          # 比较 commit SHA
          if [ "$UPSTREAM_SHA" != "$LAST_SHA" ]; then
            echo "has_update=true" >> $GITHUB_OUTPUT
            echo "New update detected in upstream repository"
          else
            echo "has_update=false" >> $GITHUB_OUTPUT
            echo "No updates in upstream repository"
          fi
          
          # 保存当前 SHA 供下次比较
          echo "$UPSTREAM_SHA" > .last_commit

  update-plugin:
    needs: check-upstream
    if: ${{ needs.check-upstream.outputs.has_update == 'true' || github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y wget jq
          
      - name: Download wy.js
        run: |
          # 使用 wget 下载文件
          wget -O wy.js "https://ghproxy.cn/raw.githubusercontent.com/ThomasBy2025/musicfree/main/plugins/wy.js"
          
          # 验证下载结果
          if [ ! -f wy.js ]; then
            echo "::error::wy.js 文件下载失败"
            exit 1
          fi
          
          if [ ! -s wy.js ]; then
            echo "::error::下载的 wy.js 文件为空"
            exit 1
          fi
          
          echo "wy.js 下载成功，大小: $(wc -c <wy.js) 字节"

      - name: Download function definitions
        run: |
          # 下载函数定义文件
          wget -O getLyric.txt "https://jgithub.xyz/Lmlanmei64/MusicFreePlugins/raw/master/getLyric.txt"
          wget -O formatComment.txt "https://jgithub.xyz/Lmlanmei64/MusicFreePlugins/raw/master/formatComment.txt"
          wget -O getMusicComments.txt "https://jgithub.xyz/Lmlanmei64/MusicFreePlugins/raw/master/getMusicComments.txt"
          
          # 验证下载结果
          for file in getLyric.txt formatComment.txt getMusicComments.txt; do
            if [ ! -f "$file" ]; then
              echo "::error::$file 下载失败"
              exit 1
            fi
            if [ ! -s "$file" ]; then
              echo "::error::$file 文件为空"
              exit 1
            fi
            echo "$file 下载成功，大小: $(wc -c <"$file") 字节"
          done

      - name: Load function codes
        run: |
          # 从文件加载函数代码
          getLyric_code=$(cat getLyric.txt)
          formatComment_code=$(cat formatComment.txt)
          getMusicComments_code=$(cat getMusicComments.txt)
          
          # 安全地设置多行环境变量
          echo "getLyric_code<<EOF" >> $GITHUB_ENV
          echo "$getLyric_code" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
          
          echo "formatComment_code<<EOF" >> $GITHUB_ENV
          echo "$formatComment_code" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
          
          echo "getMusicComments_code<<EOF" >> $GITHUB_ENV
          echo "$getMusicComments_code" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Modify wy.js functions
        run: |
          # 调试输出函数代码长度
          echo "getLyric_code length: ${#getLyric_code}"
          echo "formatComment_code length: ${#formatComment_code}"
          echo "getMusicComments_code length: ${#getMusicComments_code}"
          
          # 确保函数代码不为空
          if [ -z "${{ env.getLyric_code }}" ]; then
            echo "::error::getLyric_code 为空"
            exit 1
          fi
          
          if [ -z "${{ env.formatComment_code }}" ]; then
            echo "::error::formatComment_code 为空"
            exit 1
          fi
          
          if [ -z "${{ env.getMusicComments_code }}" ]; then
            echo "::error::getMusicComments_code 为空"
            exit 1
          fi
          
          # 使用 awk 替换函数
          awk -v getLyric="${{ env.getLyric_code }}" \
              -v formatComment="${{ env.formatComment_code }}" \
              -v getMusicComments="${{ env.getMusicComments_code }}" '
          BEGIN { RS = "" }
          {
              # 替换函数定义
              gsub(/async function getLyric\([^{]*{[^}]*}/, getLyric)
              gsub(/function formatComment\([^{]*{[^}]*}/, formatComment)
              gsub(/async function getMusicComments\([^{]*{[^}]*}/, getMusicComments)
              print
          }' wy.js > wy_modified.js
          
          # 验证修改结果
          if [ ! -s wy_modified.js ]; then
            echo "::error::修改后的文件为空"
            exit 1
          fi
          
          mv wy_modified.js wy.js
          echo "函数替换完成，新文件大小: $(wc -c <wy.js) 字节"
          
      - name: Replace srcUrl
        run: |
          # 替换 srcUrl 为新地址
          new_srcUrl="https://testingcf.jsdelivr.net/gh/Lmlanmei64/MusicFreePlugins@master/plugins/wy.js"
          
          # 使用 sed 替换 srcUrl
          sed -i "s|srcUrl: ['\"][^'\"]*['\"]|srcUrl: '$new_srcUrl'|" wy.js
          
          # 验证替换结果
          if grep -q "$new_srcUrl" wy.js; then
            echo "srcUrl 替换成功"
          else
            echo "::error::srcUrl 替换失败"
            exit 1
          fi
          
          echo "srcUrl 更新为: $new_srcUrl"

      - name: Upload modified file
        run: |
          mkdir -p plugins
          mv wy.js plugins/
          echo "文件已移动到 plugins/ 目录"

      - name: Commit changes
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "GitHub Actions"
          
          # 添加修改的文件
          git add plugins/wy.js
          
          # 仅在非手动运行且文件存在时添加 .last_commit
          if [ "${{ github.event_name }}" != "workflow_dispatch" ] && [ -f .last_commit ]; then
            git add .last_commit
          fi
          
          # 检查是否有需要提交的更改
          if git diff-index --quiet HEAD; then
            echo "没有需要提交的更改"
          else
            # 根据触发方式设置不同的提交信息
            if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
              COMMIT_MSG="chore: manual update wy.js plugin [skip ci]"
            else
              COMMIT_MSG="chore: auto update wy.js plugin from upstream [skip ci]"
            fi
            
            git commit -m "$COMMIT_MSG"
            git push
          fi