name: Update wy.js Plugin

on:
  repository_dispatch:
    types: [check_for_updates]
  workflow_dispatch:
  schedule:
    - cron: '*/10 * * * *'

jobs:
  check-upstream:
    runs-on: ubuntu-latest
    outputs:
      has_update: ${{ steps.check-update.outputs.has_update }}
    steps:
      - name: Check upstream repository status
        id: check-update
        run: |
          # 安装依赖
          sudo apt-get update
          sudo apt-get install -y jq curl
          
          # 获取上游仓库最新 commit SHA
          UPSTREAM_SHA=$(curl -s "https://api.github.com/repos/ThomasBy2025/musicfree/commits/main" | jq -r .sha)
          
          # 获取上次记录的 commit SHA
          if [ -f .last_commit ]; then
            LAST_SHA=$(cat .last_commit)
          else
            LAST_SHA=""
          fi
          
          # 比较 commit SHA
          if [ "$UPSTREAM_SHA" != "$LAST_SHA" ]; then
            echo "has_update=true" >> $GITHUB_OUTPUT
            echo "New update detected in upstream repository"
          else
            echo "has_update=false" >> $GITHUB_OUTPUT
            echo "No updates in upstream repository"
          fi
          
          # 保存当前 SHA 供下次比较
          echo "$UPSTREAM_SHA" > .last_commit

  update-plugin:
    needs: check-upstream
    if: ${{ needs.check-upstream.outputs.has_update == 'true' || github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y wget jq
          
      - name: Download wy.js
        run: |
          # 使用 wget 下载文件
          wget -O wy.js "https://ghproxy.cn/raw.githubusercontent.com/ThomasBy2025/musicfree/main/plugins/wy.js"
          
          # 验证下载结果
          if [ ! -f wy.js ]; then
            echo "::error::wy.js 文件下载失败"
            exit 1
          fi
          
          if [ ! -s wy.js ]; then
            echo "::error::下载的 wy.js 文件为空"
            exit 1
          fi
          
          echo "wy.js 下载成功，大小: $(wc -c <wy.js) 字节"

      - name: Download function definitions
        run: |
          # 下载函数定义文件
          wget -O getLyric.txt "https://ghproxy.cn/raw.githubusercontent.com/Lmlanmei64/MusicFreePlugins/master/getLyric.txt"
          wget -O formatComment.txt "https://ghproxy.cn/raw.githubusercontent.com/Lmlanmei64/MusicFreePlugins/master/formatComment.txt"
          wget -O getMusicComments.txt "https://ghproxy.cn/raw.githubusercontent.com/Lmlanmei64/MusicFreePlugins/master/getMusicComments.txt"
          
          # 验证下载结果
          for file in getLyric.txt formatComment.txt getMusicComments.txt; do
            if [ ! -f "$file" ]; then
              echo "::error::$file 下载失败"
              exit 1
            fi
            if [ ! -s "$file" ]; then
              echo "::error::$file 文件为空"
              exit 1
            fi
            echo "$file 下载成功，大小: $(wc -c <"$file") 字节"
          done

      - name: Create Node.js replacement script
        run: |
          # 创建安全的 Node.js 替换脚本
          cat > replace-functions.js << 'EOL'
          const fs = require('fs');
          const path = require('path');
          
          // 读取源文件和函数定义
          const sourceFile = fs.readFileSync('wy.js', 'utf-8');
          const functions = {
            getLyric: fs.readFileSync('getLyric.txt', 'utf-8'),
            formatComment: fs.readFileSync('formatComment.txt', 'utf-8'),
            getMusicComments: fs.readFileSync('getMusicComments.txt', 'utf-8')
          };
          
          // 定义替换函数
          function replaceFunction(source, funcName, newCode) {
            // 构建匹配函数签名的正则表达式
            const signaturePattern = new RegExp(
              `(async\\s+)?function\\s+${funcName}\\s*\\([^)]*\\)\\s*{[^}]*}`,
              'g'
            );
            
            // 尝试匹配原始函数
            const matches = source.match(signaturePattern);
            if (!matches || matches.length === 0) {
              console.error(`未找到函数: ${funcName}`);
              return source;
            }
            
            // 替换所有匹配项
            return source.replace(signaturePattern, newCode);
          }
          
          // 执行所有替换
          let modifiedContent = sourceFile;
          for (const [funcName, funcCode] of Object.entries(functions)) {
            modifiedContent = replaceFunction(modifiedContent, funcName, funcCode);
          }
          
          // 写入修改后的文件
          fs.writeFileSync('wy_modified.js', modifiedContent);
          console.log('函数替换完成');
          EOL
          
          echo "Node.js 替换脚本已创建"

      - name: Run Node.js replacement
        run: |
          # 运行 Node.js 替换脚本
          node replace-functions.js
          
          # 验证替换结果
          if [ ! -f wy_modified.js ]; then
            echo "::error::修改后的文件未生成"
            exit 1
          fi
          
          if [ ! -s wy_modified.js ]; then
            echo "::error::修改后的文件为空"
            exit 1
          fi
          
          mv wy_modified.js wy.js
          echo "函数替换成功，新文件大小: $(wc -c <wy.js) 字节"

            - name: Replace srcUrl
        run: |
          # 替换 srcUrl 为新地址
          new_srcUrl="https://testingcf.jsdelivr.net/gh/Lmlanmei64/MusicFreePlugins@master/plugins/wy.js"
          
          # 使用 Node.js 安全替换 srcUrl
          node -e "
            const fs = require('fs');
            const content = fs.readFileSync('wy.js', 'utf-8');
            const newContent = content.replace(
              /(srcUrl:\\s*['\"])([^'\"]+)(['\"])/,
              `$1${'$new_srcUrl'}$3`
            );
            fs.writeFileSync('wy.js', newContent);
            console.log('srcUrl 替换完成');
          "
          
      - name: Upload modified file
        run: |
          mkdir -p plugins
          mv wy.js plugins/
          echo "文件已移动到 plugins/ 目录"

      - name: Commit changes
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "GitHub Actions"
          
          # 添加修改的文件
          git add plugins/wy.js
          
          # 仅在非手动运行且文件存在时添加 .last_commit
          if [ "${{ github.event_name }}" != "workflow_dispatch" ] && [ -f .last_commit ]; then
            git add .last_commit
          fi
          
          # 检查是否有需要提交的更改
          if git diff-index --quiet HEAD; then
            echo "没有需要提交的更改"
          else
            # 根据触发方式设置不同的提交信息
            if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
              COMMIT_MSG="chore: manual update wy.js plugin [skip ci]"
            else
              COMMIT_MSG="chore: auto update wy.js plugin from upstream [skip ci]"
            fi
            
            git commit -m "$COMMIT_MSG"
            git push
          fi